[package]
name = "import"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
log = {version="0.4",registry="susytech"}
primitives = { path = "../primitives" }
chain = { path = "../chain" }
serialization = { path = "../serialization" }
